// 模拟数据：航班搜索结果
const flightSearchResults = [
  {
    id: '1',
    flightNumber: 'CA1234',
    departure: '北京',
    arrival: '上海',
    departureTime: '2026-03-15 10:00',
    arrivalTime: '2026-03-15 12:00',
    price: 1000,
    detailInfo: {
      baggage: '1 checked bag',
      cabinClass: 'Economy',
      aircraft: 'Boeing 737-800',
      duration: '2h',
      stops: 0,
      nextDay: false,
      departureTime: '2026-03-15 10:00',
      arrivalTime: '2026-03-15 12:00',
      price: 1000,
      comfortInfo: {
        wifi: true,
        seat: 'Economy',
        meal: 'Economy',
        entertainment: 'Economy',
        noise: 'Economy',
      },
    },
  },
  {
    id: '2',
    flightNumber: 'CA1235',
    departure: '北京',
    arrival: '上海',
    departureTime: '2026-03-15 10:00',
    arrivalTime: '2026-03-15 12:00',
    price: 1000,
    detailInfo: {
      baggage: '1 checked bag',
      cabinClass: 'Economy',
      aircraft: 'Boeing 737-800',
      duration: '2h',
      stops: 0,
      nextDay: false,
    },
    comfortInfo: {
      wifi: true,
      seat: 'Economy',
      meal: 'Economy',
      entertainment: 'Economy',
      noise: 'Economy',
    },
  },
  {
    id: '6',
    flightNumber: 'CA1236',
    departure: '北京',
    arrival: '上海',
    departureTime: '2026-03-15 10:00',
    arrivalTime: '2026-03-15 12:00',
    price: 1000,
    detailInfo: {
      baggage: '1 checked bag',
      cabinClass: 'Economy',
      aircraft: 'Boeing 737-800',
      duration: '2h',
      stops: 0,
      nextDay: false,
    },
    comfortInfo: {
      wifi: true,
      seat: 'Economy',
      meal: 'Economy',
      entertainment: 'Economy',
      noise: 'Economy',
    },
  },
  {
    id: '3',
    flightNumber: 'CA1237',
    departure: '北京',
    arrival: '上海',
    departureTime: '2026-03-15 10:00',
    arrivalTime: '2026-03-15 12:00',
    price: 1000,
    detailInfo: {
      baggage: '1 checked bag',
      cabinClass: 'Economy',
      aircraft: 'Boeing 737-800',
      duration: '2h',
      stops: 0,
      nextDay: false,
    },
    comfortInfo: {
      wifi: true,
      seat: 'Economy',
      meal: 'Economy',
      entertainment: 'Economy',
      noise: 'Economy',
    },
  },
  {
    id: '4',
    flightNumber: 'CA1238',
    departure: '北京',
    arrival: '上海',
    departureTime: '2026-03-15 10:00',
    arrivalTime: '2026-03-15 12:00',
    price: 1000,
    detailInfo: {
      baggage: '1 checked bag',
      cabinClass: 'Economy',
      aircraft: 'Boeing 737-800',
      duration: '2h',
      stops: 0,
      nextDay: false,
    },
    comfortInfo: {
      wifi: true,
      seat: 'Economy',
      meal: 'Economy',
      entertainment: 'Economy',
      noise: 'Economy',
    },
  },
  {
    id: '5',
    flightNumber: 'CA1239',
    departure: '北京',
    arrival: '上海',
    departureTime: '2026-03-15 10:00',
    arrivalTime: '2026-03-15 12:00',
    price: 1000,
    detailInfo: {
      baggage: '1 checked bag',
      cabinClass: 'Economy',
      aircraft: 'Boeing 737-800',
      duration: '2h',
      stops: 0,
      nextDay: false,
    },
    comfortInfo: {
      wifi: true,
      seat: 'Economy',
      meal: 'Economy',
      entertainment: 'Economy',
      noise: 'Economy',
    },
  },
  {
    id: '6',
    flightNumber: 'CA1240',
    departure: '北京',
    arrival: '上海',
    departureTime: '2026-03-15 10:00',
    arrivalTime: '2026-03-15 12:00',
    price: 1000,
    detailInfo: {
      baggage: '1 checked bag',
      cabinClass: 'Economy',
      aircraft: 'Boeing 737-800',
      duration: '2h',
      stops: 0,
      nextDay: false,
    },
    comfortInfo: {
      wifi: true,
      seat: 'Economy',
      meal: 'Economy',
      entertainment: 'Economy',
      noise: 'Economy',
    },
  },
] as const;

export { flightSearchResults };
