### 开始对话
POST http://localhost:3000/service/langchain/basic
Content-Type: application/json

{
  "humanMessage": "列出当前目录的文件结构"
}

### 开始对话
POST http://localhost:3000/service/langchain/basic
Content-Type: application/json

{
  "humanMessage": "为 apps/web/app/service/__tests__/langchain/basic.http 增加 3 个测试用例，测试工具的执行结果"
}